### PR TITLE
Fix Help Command bugs

### LINKED ISSUE #273: [PE-D] help command: entering extra parameters
In the case when a user enters parameter(s) after the 'help' keyword, while help is still functional, perhaps it would be better to give an error message, as the user most likely expects help to be for a certain command.

Before:

After:

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: eugenetyc/ped#4

### LINKED ISSUE #275: [PE-D] help pop-up window has no option to close.
Upon typing 'help', I can't find a clear way to close it/not obvious way for user to close. The only way I found was to hover over the icon in the windows application and click x, which some users won't think of. Alternatively, could decrease the help window's height and increase the width to show the window close option and fit it within the computer monitor.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: eugenetyc/ped#2

### LINKED ISSUE #280: [PE-D] Help window size
Help window size is too big, unable to see the menu bar.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: sp-shaopeng/ped#2

### LINKED ISSUE #286: [PE-D] Help window is larger than my PC screen
Help window larger than my PC screen and the window is not resizable. Thus, I cannot access the menu bar and the window cannot be closed normally.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zenatrick/ped#2

### LINKED ISSUE #295: [PE-D] Documentation issue
The instruction at the help window is not updated.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Weiichengg/ped#4

### PR DESCRIPTION
**Pull request by Cherweijie**
#295, #286, #280, #275, #273

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/HelpCommandParser.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+     * @param argument
+     * @return true if user input includes extra parameters and false otherwise
+     */
+    private boolean doesInputHaveExtraParameters(String argument) {
+        if (argument.equals("")) {
+            return false;
+        } else {
+            return true;
+        }
+    }
```
Comment (JeremyLoh) [inline src/main/java/seedu/address/logic/parser/HelpCommandParser.java]: Maybe this could be `return !argument.equals("")` or you could remove the else statement, and return true by default

**Review by khsc96 — COMMENTED** [review]
Looks good except minor changes mentioned by Jeremy. Good job!

**Review by JeremyLoh — APPROVED** [review]
LGTM. Thanks! 👍

**Review by khsc96 — APPROVED** [review]
LGTM, good job!
